/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pemilu;

import java.awt.Font;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author RPL 4_10
 */
public class Pemilu extends javax.swing.JFrame {

    /**
     * Creates new form Pemilu
     */
    public Pemilu() {
        initComponents();
        
        jInputCount.setBackground(new Color(0, 0, 0, 1));
        jInputPercent.setBackground(new Color(0, 0, 0, 1));
        
        jTable1.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        jTable1.getTableHeader().setOpaque(false);
        jTable1.getTableHeader().setBackground(new Color(235, 51, 11));
        jTable1.getTableHeader().setForeground(new Color(235, 51, 11));
        
        jTable2.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        jTable2.getTableHeader().setOpaque(false);
        jTable2.getTableHeader().setBackground(new Color(235, 51, 11));
        jTable2.getTableHeader().setForeground(new Color(235, 51, 11));
        
        jTable3.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        jTable3.getTableHeader().setOpaque(false);
        jTable3.getTableHeader().setBackground(new Color(235, 51, 11));
        jTable3.getTableHeader().setForeground(new Color(235, 51, 11));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jSelectPerson = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jProvince = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jInputCount = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jInputPercent = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jSave = new java.awt.Button();
        jClear = new java.awt.Button();
        jEdit = new java.awt.Button();
        jExit = new java.awt.Button();
        jDelete = new java.awt.Button();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RAPIDCOUNT - Pemilu 2024");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/the-general-election-committee-regency-indonesian-regional-election-komisi-pemilihan-umum-pamekasan-kpu-logo-a46c3e58b96743c72a2c677ad0939ea3 (1).png"))); // NOI18N
        jLabel1.setText("RAPIDCOUNT PEMILU 2024");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/anies_1.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/ganjar_1.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/prabowo_1.png"))); // NOI18N

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Provinsi", "Suara", "Jumlah"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable2);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Provinsi", "Suara", "Jumlah"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Provinsi", "Suara", "Jumlah"
            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(127, 127, 127))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 450));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jSelectPerson.setBackground(new java.awt.Color(255, 51, 51));
        jSelectPerson.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03" }));
        jSelectPerson.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));
        jSelectPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSelectPersonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Yu Gothic", 0, 10)); // NOI18N
        jLabel7.setText("Silahkan pilih paslon yang akan diubah datanya");

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 17)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 51, 51));
        jLabel8.setText("DATA");

        jProvince.setBackground(new java.awt.Color(255, 51, 51));
        jProvince.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACEH", "BALI", "BANTEN", "BENGKULU", "DAERAH ISTIMEWA YOGYAKARTA", "DKI JAKARTA", "GORONTALO", "JAMBI", "JAWA BARAT", "JAWA TENGAH", "JAWA TIMUR", "KALIMANTAN BARAT", "KALIMANTAN SELATAN", "KALIMANTAN TENGAH", "KALIMANTAN TIMUR", "KALIMANTAN UTARA", "KEPULAUAN BANGKA BELITUNG", "KEPULAUAN RIAU", "LAMPUNG", "MALUKU", "MALUKU UTARA", "NUSA TENGGARA BARAT", "NUSA TENGGARA TIMUR", "PAPUA", "PAPUA BARAT", "PAPUA BARAT DAYA", "PAPUA PEGUNUNGAN", "PAPUA SELATAN", "PAPUA TENGAH", "RIAU", "SULAWESI BARAT", "SULAWESI SELATAN", "SULAWESI TENGAH", "SULAWESI TENGGARA", "SULAWESI UTARA", "SUMATERA BARAT", "SUMATERA SELATAN", "SUMATERA UTARA", "Luar Negeri" }));

        jLabel9.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 51, 51));
        jLabel9.setText("Provinsi");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/city-country-location-svgrepo-com.png"))); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/person-svgrepo-com.png"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 51, 51));
        jLabel12.setText("Jumlah Suara");

        jInputCount.setBorder(null);
        jInputCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInputCountActionPerformed(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/number-svgrepo-com.png"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 51, 51));
        jLabel14.setText("Persentase");

        jInputPercent.setBorder(null);
        jInputPercent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInputPercentActionPerformed(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/percent-svgrepo-com.png"))); // NOI18N

        jSave.setActionCommand("jSave");
        jSave.setBackground(new java.awt.Color(255, 51, 51));
        jSave.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 12)); // NOI18N
        jSave.setLabel("SIMPAN");
        jSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSaveMouseClicked(evt);
            }
        });
        jSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveActionPerformed(evt);
            }
        });

        jClear.setActionCommand("jClear");
        jClear.setBackground(new java.awt.Color(255, 51, 51));
        jClear.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 12)); // NOI18N
        jClear.setLabel("BERSIHKAN");
        jClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jClearMouseClicked(evt);
            }
        });
        jClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClearActionPerformed(evt);
            }
        });

        jEdit.setActionCommand("jEdit");
        jEdit.setBackground(new java.awt.Color(255, 51, 51));
        jEdit.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 12)); // NOI18N
        jEdit.setLabel("EDIT");
        jEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jEditMouseClicked(evt);
            }
        });
        jEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditActionPerformed(evt);
            }
        });

        jExit.setActionCommand("jExit");
        jExit.setBackground(new java.awt.Color(255, 51, 51));
        jExit.setFont(new java.awt.Font("SansSerif", 1, 8)); // NOI18N
        jExit.setLabel("KELUAR");
        jExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jExitMouseClicked(evt);
            }
        });
        jExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitActionPerformed(evt);
            }
        });

        jDelete.setActionCommand("jDelete");
        jDelete.setBackground(new java.awt.Color(255, 51, 51));
        jDelete.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 12)); // NOI18N
        jDelete.setLabel("HAPUS");
        jDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDeleteMouseClicked(evt);
            }
        });
        jDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(121, 121, 121))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel9)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jInputPercent, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jInputCount, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jProvince, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                                                .addComponent(jSelectPerson, javax.swing.GroupLayout.Alignment.LEADING, 0, 147, Short.MAX_VALUE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel15)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jSave, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jClear, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jExit, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jSelectPerson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jProvince, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jInputCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jInputPercent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(jExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jSave.getAccessibleContext().setAccessibleName("jSave");
        jClear.getAccessibleContext().setAccessibleName("jClear");
        jEdit.getAccessibleContext().setAccessibleName("jEdit");
        jExit.getAccessibleContext().setAccessibleName("jExit");

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, -2, 290, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jInputCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInputCountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jInputCountActionPerformed

    private void jInputPercentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInputPercentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jInputPercentActionPerformed

    private void jSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSaveActionPerformed

    private void jClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jClearActionPerformed

    private void jEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEditActionPerformed

    private void jExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jExitActionPerformed

    private void jDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDeleteActionPerformed

    private void jSelectPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSelectPersonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSelectPersonActionPerformed

    private void jSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSaveMouseClicked
        // TODO add your handling code here:
        String person = (String) jSelectPerson.getSelectedItem();
        String province = jProvince.getSelectedItem().toString();
        if(person.equals("01")) {
            DefaultTableModel dataModel = (DefaultTableModel) jTable1.getModel();
            jTable1.setAutoCreateColumnsFromModel(true);
            var list = new ArrayList<>();
            list.add(province);
            list.add(jInputCount.getText());
            list.add(jInputPercent.getText());
            dataModel.addRow(list.toArray());
            jInputCount.setText("");
            jInputPercent.setText("");
        } else if(person.equals("02")) {
            DefaultTableModel dataModel = (DefaultTableModel) jTable2.getModel();
            jTable2.setAutoCreateColumnsFromModel(true);
            var list = new ArrayList<>();
            list.add(province);
            list.add(jInputCount.getText());
            list.add(jInputPercent.getText());
            dataModel.addRow(list.toArray());
            jInputCount.setText("");
            jInputPercent.setText("");
        } else {
            DefaultTableModel dataModel = (DefaultTableModel) jTable3.getModel();
            jTable3.setAutoCreateColumnsFromModel(true);
            var list = new ArrayList<>();
            list.add(province);
            list.add(jInputCount.getText());
            list.add(jInputPercent.getText());
            dataModel.addRow(list.toArray());
            jInputCount.setText("");
            jInputPercent.setText("");
        }
    }//GEN-LAST:event_jSaveMouseClicked

    private void jExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jExitMouseClicked

    private void jEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jEditMouseClicked
        // TODO add your handling code here:
        String person = (String) jSelectPerson.getSelectedItem();
        String province = jProvince.getSelectedItem().toString();
        if(person.equals("01")) {
            DefaultTableModel data01Model = (DefaultTableModel) jTable1.getModel();
            if(jTable1.getSelectedRowCount () == 1){
            
            String Edit01Province = province;
            String Edit01Count = jInputCount.getText();
            String Edit01Persen = jInputPercent.getText();
            
            data01Model.setValueAt(Edit01Province, jTable1.getSelectedRow(), 0);
            data01Model.setValueAt(Edit01Count, jTable1.getSelectedRow(), 1);
            data01Model.setValueAt(Edit01Persen, jTable1.getSelectedRow(), 2);
            JOptionPane.showMessageDialog(this, "Berhasil Edit Data");
            }else{
                if(jTable1.getRowCount()==0){
                JOptionPane.showMessageDialog(this, "Tabel Kosong");
                } else {
                JOptionPane.showMessageDialog(this, "Silahkan pilih baris yang akan diedit!");
                }
            }
        } else if(person.equals("02")) {
            DefaultTableModel data02Model = (DefaultTableModel) jTable2.getModel();
            if(jTable2.getSelectedRowCount () == 1){
            
            String Edit02Province = province;
            String Edit02Count = jInputCount.getText();
            String Edit02Persen = jInputPercent.getText();
            
            data02Model.setValueAt(Edit02Province, jTable2.getSelectedRow(), 0);
            data02Model.setValueAt(Edit02Count, jTable2.getSelectedRow(), 1);
            data02Model.setValueAt(Edit02Persen, jTable2.getSelectedRow(), 2);
            JOptionPane.showMessageDialog(this, "Berhasil Edit Data");
            }else{
                if(jTable2.getRowCount()==0){
                JOptionPane.showMessageDialog(this, "Tabel Kosong");
                } else {
                JOptionPane.showMessageDialog(this, "Silahkan pilih baris yang akan diedit!");
                }
            }
        } else if(person.equals("03")) {
            DefaultTableModel data03Model = (DefaultTableModel) jTable3.getModel();
            if(jTable3.getSelectedRowCount () == 1){
            
            String Edit03Province = province;
            String Edit03Count = jInputCount.getText();
            String Edit03Persen = jInputPercent.getText();
            
            data03Model.setValueAt(Edit03Province, jTable3.getSelectedRow(), 0);
            data03Model.setValueAt(Edit03Count, jTable3.getSelectedRow(), 1);
            data03Model.setValueAt(Edit03Persen, jTable3.getSelectedRow(), 2);
            JOptionPane.showMessageDialog(this, "Berhasil Edit Data");
            }else{
                if(jTable3.getRowCount()==0){
                JOptionPane.showMessageDialog(this, "Tabel Kosong");
                } else {
                JOptionPane.showMessageDialog(this, "Silahkan pilih baris yang akan diedit!");
                }
            }
        }
    }//GEN-LAST:event_jEditMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel data01Model = (DefaultTableModel) jTable1.getModel();
        
        String Province01Row = data01Model.getValueAt(jTable1.getSelectedRow(), 0).toString();
        String Count01Row = data01Model.getValueAt(jTable1.getSelectedRow(), 1).toString();
        String Persen01Row = data01Model.getValueAt(jTable1.getSelectedRow(), 2).toString();
        
        jProvince.setSelectedItem(Province01Row);
        jInputCount.setText(Count01Row);
        jInputPercent.setText(Persen01Row);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        DefaultTableModel data02Model = (DefaultTableModel) jTable2.getModel();
        
        String Province02Row = data02Model.getValueAt(jTable2.getSelectedRow(), 0).toString();
        String Count02Row = data02Model.getValueAt(jTable2.getSelectedRow(), 1).toString();
        String Persen02Row = data02Model.getValueAt(jTable2.getSelectedRow(), 2).toString();
        
        jProvince.setSelectedItem(Province02Row);
        jInputCount.setText(Count02Row);
        jInputPercent.setText(Persen02Row);
    }//GEN-LAST:event_jTable2MouseClicked

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        // TODO add your handling code here:
        DefaultTableModel data03Model = (DefaultTableModel) jTable3.getModel();
        
        String Province03Row = data03Model.getValueAt(jTable3.getSelectedRow(), 0).toString();
        String Count03Row = data03Model.getValueAt(jTable3.getSelectedRow(), 1).toString();
        String Persen03Row = data03Model.getValueAt(jTable3.getSelectedRow(), 2).toString();
        
        jProvince.setSelectedItem(Province03Row);
        jInputCount.setText(Count03Row);
        jInputPercent.setText(Persen03Row);
    }//GEN-LAST:event_jTable3MouseClicked

    private void jClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jClearMouseClicked
        // TODO add your handling code here:
        String person = (String) jSelectPerson.getSelectedItem();
        if(person.equals("01")) {
            DefaultTableModel dataModel = (DefaultTableModel) jTable1.getModel();
            dataModel.setRowCount(0);
            revalidate();
        } else if(person.equals("02")) {
            DefaultTableModel dataModel = (DefaultTableModel) jTable2.getModel();
            dataModel.setRowCount(0);
            revalidate();
        } else {
            DefaultTableModel dataModel = (DefaultTableModel) jTable3.getModel();
            dataModel.setRowCount(0);
            revalidate();
        }
        
    }//GEN-LAST:event_jClearMouseClicked

    private void jDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDeleteMouseClicked
        // TODO add your handling code here:
        DefaultTableModel data01Model = (DefaultTableModel) jTable1.getModel();
        DefaultTableModel data02Model = (DefaultTableModel) jTable2.getModel();
        DefaultTableModel data03Model = (DefaultTableModel) jTable3.getModel();
        String person = (String) jSelectPerson.getSelectedItem();
        if(person.equals("01")) {
            try{
              int SelectedRowIndex = jTable1.getSelectedRow();
              data01Model.removeRow(SelectedRowIndex);
            }catch(Exception ex)
              {
                JOptionPane.showMessageDialog(null, ex);
              }
        } else if(person.equals("02")) {
            try{
              int SelectedRowIndex = jTable2.getSelectedRow();
              data02Model.removeRow(SelectedRowIndex);
            }catch(Exception ex)
              {
                JOptionPane.showMessageDialog(null, ex);
              }
        } else {
            try{
              int SelectedRowIndex = jTable3.getSelectedRow();
              data03Model.removeRow(SelectedRowIndex);
            }catch(Exception ex)
              {
                JOptionPane.showMessageDialog(null, ex);
              }
        }
    }//GEN-LAST:event_jDeleteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pemilu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pemilu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pemilu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pemilu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pemilu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button jClear;
    private java.awt.Button jDelete;
    private java.awt.Button jEdit;
    private java.awt.Button jExit;
    private javax.swing.JTextField jInputCount;
    private javax.swing.JTextField jInputPercent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> jProvince;
    private java.awt.Button jSave;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JComboBox<String> jSelectPerson;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    // End of variables declaration//GEN-END:variables
}
