/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PemiluPackage;

import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author RPL 3_24
 */
public class Pemilu extends javax.swing.JFrame {

    /**
     * Creates new form Pemilu
     */
    public Pemilu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable01 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable03 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable02 = new javax.swing.JTable();
        j03ProvinceField = new javax.swing.JTextField();
        j02CountField = new javax.swing.JTextField();
        j02PersenField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jExitButton = new javax.swing.JButton();
        j03SaveButton = new javax.swing.JButton();
        j03EditButton = new javax.swing.JButton();
        j03DeleteButton = new javax.swing.JButton();
        j03ClearButton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        j03CountField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        j03PersenField = new javax.swing.JTextField();
        j02EditButton = new javax.swing.JButton();
        j02SaveButton = new javax.swing.JButton();
        j02ClearButton = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        j02ProvinceField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        j01PersenField = new javax.swing.JTextField();
        j01EditButton = new javax.swing.JButton();
        j01ClearButton = new javax.swing.JButton();
        j02DeleteButton = new javax.swing.JButton();
        j01SaveButton = new javax.swing.JButton();
        j01DeleteButton = new javax.swing.JButton();
        j01ProvinceField = new javax.swing.JTextField();
        j01CountField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(245, 112, 35));

        jLabel2.setFont(new java.awt.Font("Schadow BT", 3, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\RPL 3_24\\Downloads\\the-general-election-committee-regency-indonesian-regional-election-komisi-pemilihan-umum-pamekasan-kpu-logo-a46c3e58b96743c72a2c677ad0939ea3 (1).png")); // NOI18N
        jLabel2.setText("KPU Republik Indonesia");

        jLabel3.setFont(new java.awt.Font("Stencil", 1, 14)); // NOI18N
        jLabel3.setText("PENCATATAN HASIL PEMILU 2024");

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\RPL 3_24\\Downloads\\infografis-tampilan-paslon-di-surat-suara-pilpres-2024-1 (2) (1).jpeg")); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\RPL 3_24\\Downloads\\infografis-tampilan-paslon-di-surat-suara-pilpres-2024-1 (4).jpeg")); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\RPL 3_24\\Downloads\\infografis-tampilan-paslon-di-surat-suara-pilpres-2024-1 (5).jpeg")); // NOI18N

        jTable01.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Provinsi", "Jml Suara", "Persentase"
            }
        ));
        jScrollPane1.setViewportView(jTable01);

        jTable03.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Provinsi", "Jml Suara", "Persentase"
            }
        ));
        jScrollPane2.setViewportView(jTable03);

        jTable02.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Provinsi", "Jml Suara", "Persentase"
            }
        ));
        jScrollPane3.setViewportView(jTable02);

        j02PersenField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j02PersenFieldActionPerformed(evt);
            }
        });

        jLabel8.setText("Provinsi :");

        jLabel9.setText("Suara :");

        jLabel10.setText("Persentase :");

        jExitButton.setText("Keluar");
        jExitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jExitButtonMouseClicked(evt);
            }
        });
        jExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitButtonActionPerformed(evt);
            }
        });

        j03SaveButton.setText("Simpan");
        j03SaveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j03SaveButtonMouseClicked(evt);
            }
        });

        j03EditButton.setText("Edit");
        j03EditButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j03EditButtonMouseClicked(evt);
            }
        });

        j03DeleteButton.setText("Hapus");
        j03DeleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j03DeleteButtonMouseClicked(evt);
            }
        });

        j03ClearButton.setText("Bersihkan Kolom");
        j03ClearButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j03ClearButtonMouseClicked(evt);
            }
        });

        jLabel12.setText("Provinsi :");

        jLabel13.setText("Suara :");

        j03CountField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j03CountFieldActionPerformed(evt);
            }
        });

        jLabel14.setText("Persentase :");

        j02EditButton.setText("Edit");
        j02EditButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j02EditButtonMouseClicked(evt);
            }
        });

        j02SaveButton.setText("Simpan");
        j02SaveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j02SaveButtonMouseClicked(evt);
            }
        });

        j02ClearButton.setText("Bersihkan Kolom");
        j02ClearButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j02ClearButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                j02ClearButtonMouseEntered(evt);
            }
        });

        jLabel15.setText("Provinsi :");

        jLabel16.setText("Suara :");

        jLabel17.setText("Persentase :");

        j01EditButton.setText("Edit");
        j01EditButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j01EditButtonMouseClicked(evt);
            }
        });

        j01ClearButton.setText("Bersihkan Kolom");
        j01ClearButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j01ClearButtonMouseClicked(evt);
            }
        });

        j02DeleteButton.setText("Hapus");
        j02DeleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j02DeleteButtonMouseClicked(evt);
            }
        });

        j01SaveButton.setText("Simpan");
        j01SaveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j01SaveButtonMouseClicked(evt);
            }
        });

        j01DeleteButton.setText("Hapus");
        j01DeleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j01DeleteButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel5)
                .addGap(232, 232, 232)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(185, 185, 185))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123)
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(j01ProvinceField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j01CountField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(j01ClearButton)
                                    .addGap(75, 75, 75)
                                    .addComponent(j01DeleteButton))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(j01EditButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(j01SaveButton))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(j01PersenField, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel15)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16)))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(j02EditButton)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(j02ClearButton)
                                    .addGap(103, 103, 103)
                                    .addComponent(j02DeleteButton))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(25, 25, 25)
                                        .addComponent(j02ProvinceField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(j02SaveButton)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel13)
                                            .addGap(38, 38, 38)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(j02PersenField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                    .addComponent(j02CountField, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(1, 1, 1)))))
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(j03ClearButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(j03DeleteButton))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(j03EditButton)
                                        .addGap(122, 122, 122)
                                        .addComponent(j03SaveButton)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel9))
                                    .addGap(26, 26, 26)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(j03CountField, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(j03ProvinceField, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(j03PersenField, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(88, 88, 88))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jExitButton)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(j03ProvinceField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(jLabel12)
                        .addComponent(j01ProvinceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(j02ProvinceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel13)
                            .addComponent(jLabel16)
                            .addComponent(j02CountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j01CountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(j02PersenField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j03PersenField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(j01PersenField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(j03EditButton)
                                .addComponent(j02SaveButton))
                            .addComponent(j03SaveButton)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(j02EditButton)
                                .addComponent(j01SaveButton)
                                .addComponent(j01EditButton))))
                    .addComponent(j03CountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(j03DeleteButton)
                    .addComponent(j03ClearButton)
                    .addComponent(j02DeleteButton)
                    .addComponent(j01DeleteButton)
                    .addComponent(j02ClearButton)
                    .addComponent(j01ClearButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jExitButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void j02PersenFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j02PersenFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j02PersenFieldActionPerformed

    private void jExitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jExitButtonMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jExitButtonMouseClicked

    private void jExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jExitButtonActionPerformed

    private void j03ClearButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j03ClearButtonMouseClicked
        // TODO add your handling code here:
        j03ProvinceField.setText("");
        j03CountField.setText("");
        j03PersenField.setText("");
    }//GEN-LAST:event_j03ClearButtonMouseClicked

    private void j03CountFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j03CountFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j03CountFieldActionPerformed

    private void j02ClearButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j02ClearButtonMouseClicked
        // TODO add your handling code here:
        j02ProvinceField.setText("");
        j02CountField.setText("");
        j02PersenField.setText("");
    }//GEN-LAST:event_j02ClearButtonMouseClicked

    private void j02ClearButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j02ClearButtonMouseEntered
        // TODO add your handlincode here:
    }//GEN-LAST:event_j02ClearButtonMouseEntered

    private void j01ClearButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j01ClearButtonMouseClicked
        // TODO add your handling code here:
        j01ProvinceField.setText("");
        j01CountField.setText("");
        j01PersenField.setText("");
    }//GEN-LAST:event_j01ClearButtonMouseClicked

    private void j01SaveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j01SaveButtonMouseClicked
        // TODO add your handling code here:
        DefaultTableModel dataModel = (DefaultTableModel) jTable01.getModel();
        var list = new ArrayList<>();
        jTable01.setAutoCreateColumnsFromModel(true);
        list.add(j01ProvinceField.getText());
        list.add(j01CountField.getText());
        list.add(j01PersenField.getText());
        dataModel.addRow(list.toArray());
    }//GEN-LAST:event_j01SaveButtonMouseClicked

    private void j01DeleteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j01DeleteButtonMouseClicked
        // TODO add your handling code here:
        DefaultTableModel data01Model = (DefaultTableModel) jTable01.getModel();
        if(jTable01.getSelectedRow() != -1) {
               // remove selected row from the model
               data01Model.removeRow(jTable01.getSelectedRow());
               JOptionPane.showMessageDialog(null, "Berhasil menghapus kolom yang dipilih!");
        }
        else {
            JOptionPane.showMessageDialog(null, "Pilih terlebih dahulu kolom yang ingin dihapus!");
        }
    }//GEN-LAST:event_j01DeleteButtonMouseClicked

    private void j02DeleteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j02DeleteButtonMouseClicked
        // TODO add your handling code here:
        DefaultTableModel data02Model = (DefaultTableModel) jTable02.getModel();
        if(jTable02.getSelectedRow() != -1) {
               // remove selected row from the model
               data02Model.removeRow(jTable02.getSelectedRow());
               JOptionPane.showMessageDialog(null, "Berhasil menghapus kolom yang dipilih!");
        }
        else {
            JOptionPane.showMessageDialog(null, "Pilih terlebih dahulu kolom yang ingin dihapus!");
        }
    }//GEN-LAST:event_j02DeleteButtonMouseClicked

    private void j03DeleteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j03DeleteButtonMouseClicked
        // TODO add your handling code here:
        DefaultTableModel data03Model = (DefaultTableModel) jTable03.getModel();
        if(jTable03.getSelectedRow() != -1) {
               // remove selected row from the model
               data03Model.removeRow(jTable03.getSelectedRow());
               JOptionPane.showMessageDialog(null, "Berhasil menghapus kolom yang dipilih!");
        }
        else {
            JOptionPane.showMessageDialog(null, "Pilih terlebih dahulu kolom yang ingin dihapus!");
        }
    }//GEN-LAST:event_j03DeleteButtonMouseClicked

    private void j02SaveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j02SaveButtonMouseClicked
        // TODO add your handling code here:
        DefaultTableModel dataModel = (DefaultTableModel) jTable02.getModel();
        var list = new ArrayList<>();
        jTable02.setAutoCreateColumnsFromModel(true);
        list.add(j02ProvinceField.getText());
        list.add(j02CountField.getText());
        list.add(j02PersenField.getText());
        dataModel.addRow(list.toArray());
    }//GEN-LAST:event_j02SaveButtonMouseClicked

    private void j03SaveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j03SaveButtonMouseClicked
        // TODO add your handling code here:
        DefaultTableModel dataModel = (DefaultTableModel) jTable03.getModel();
        var list = new ArrayList<>();
        jTable03.setAutoCreateColumnsFromModel(true);
        list.add(j03ProvinceField.getText());
        list.add(j03CountField.getText());
        list.add(j03PersenField.getText());
        dataModel.addRow(list.toArray());
    }//GEN-LAST:event_j03SaveButtonMouseClicked

    private void j01EditButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j01EditButtonMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Silahkan edit secara langsung di Tabel dengan cara klik kolom yang diedit sebanyak 2 kali!");
    }//GEN-LAST:event_j01EditButtonMouseClicked

    private void j02EditButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j02EditButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_j02EditButtonMouseClicked

    private void j03EditButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j03EditButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_j03EditButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pemilu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pemilu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pemilu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pemilu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pemilu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton j01ClearButton;
    private javax.swing.JTextField j01CountField;
    private javax.swing.JButton j01DeleteButton;
    private javax.swing.JButton j01EditButton;
    private javax.swing.JTextField j01PersenField;
    private javax.swing.JTextField j01ProvinceField;
    private javax.swing.JButton j01SaveButton;
    private javax.swing.JButton j02ClearButton;
    private javax.swing.JTextField j02CountField;
    private javax.swing.JButton j02DeleteButton;
    private javax.swing.JButton j02EditButton;
    private javax.swing.JTextField j02PersenField;
    private javax.swing.JTextField j02ProvinceField;
    private javax.swing.JButton j02SaveButton;
    private javax.swing.JButton j03ClearButton;
    private javax.swing.JTextField j03CountField;
    private javax.swing.JButton j03DeleteButton;
    private javax.swing.JButton j03EditButton;
    private javax.swing.JTextField j03PersenField;
    private javax.swing.JTextField j03ProvinceField;
    private javax.swing.JButton j03SaveButton;
    private javax.swing.JButton jExitButton;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable01;
    private javax.swing.JTable jTable02;
    private javax.swing.JTable jTable03;
    // End of variables declaration//GEN-END:variables
}
